### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by niski84** [mellium/sasl#3]
go get github.com/mellium/sasl
can't load package: package github.com/mellium/sasl: code in directory 

...\src\github.com\mellium\sasl expects import "mellium.im/sasl"

**Comment by niski84** [comment]
I changed mechanize.go to:

package sasl // import "github.com/mellium/sasl"

and anywhere it says:
	"mellium.im/sasl"

to:
	"github.com/mellium/sasl"

and re-issue the go get command and it worked.

**Comment by niski84** [comment]
when doing a `dep ensure`:

> (34)  ✗   github.com/mellium/sasl at v0.2.1 has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); required by (root).
> (33)      try github.com/mellium/sasl@v0.2.0
> (34)  ✗   github.com/mellium/sasl at v0.2.0 has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); required by (root).
> (33)      try github.com/mellium/sasl@v0.1.1
> (34)  ✗   github.com/mellium/sasl at v0.1.1 has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); required by (root).
> (33)      try github.com/mellium/sasl@v0.1.0
> (34)  ✗   github.com/mellium/sasl at v0.1.0 has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); required by (root).
> (33)      try github.com/mellium/sasl@v0.0.1
> (34)  ✗   github.com/mellium/sasl at v0.0.1 has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); required by (root).
> (33)      try github.com/mellium/sasl@master
> (34)  ✗   github.com/mellium/sasl at master has problem subpkg(s):
> (34)            github.com/mellium/sasl has err (*pkgtree.NonCanonicalImportRoot); requir

**Comment by SamWhited** [comment]
Sorry, I wasn't getting notifications for this repo somehow, but I've fixed the problem now. This is correct, the import is `mellium.im/sasl` so the GitHub address *should* fail.
